### ISSUE TITLE
Add `cljc` as a platform

### ISSUE THREAD

**Issue by arrdem** [clojure-grimoire/lib-grimoire#25]
/cc @rmoehn

There is an interesting case to be made that "clj" is "JVM Clojure" and includes all the host interop semantics thereof, while "cljc" is "Common Clojure" expected to run on any platform either by not leveraging host specific interop or reader conditionals to achive portability. As such, "cljc" is logically its own hybrid platform and should probably be listed as such.

Thoughts?

**Comment by rmoehn** [comment]
Isn't "cljc" just something that looks different depending on who loads it? At least as soon as reader conditionals are used. Something defined for one platform might be defined very differently for another platform. How would you make one set of Things from that?

Even without reader conditionals the metadata attached by the ClojureScript compiler are potentially different from those attached by the JVM Clojure compiler and again for all the other compilers. You'd have to find a unified format for the metadata and convert back and forth.

In the era before "cljc" we had "cljx" and generated different Things for each platform. I don't see why and how that should change.

**Comment by arrdem** [comment]
Yeah agreed. I guess in a perfect world we'd be able to say whether some symbol S is shared between platforms and only document/example it once, but I agree that with the "cljc depends on the loading platform" behavior that's not generally possible.
