### ISSUE TITLE
Some version strings cause exception when listed

### ISSUE THREAD

**Issue by martinklepsch** [clojure-grimoire/lib-grimoire#33]
`clojure-version->cmp-key` fails with version strings like `0.3-alpha3`

https://github.com/clojure-grimoire/lib-grimoire/blob/7159e1d3f34120bb68d5a5ca3bf4f123a3a343b0/src/grimoire/util.clj#L114-L115

**Comment by martinklepsch** [comment]
This might be a potential fix:

```clj
(let [to-long (fn [^String s] (Long/parseLong s))
      [v q] (str/split version-str #"-" 2)
      [major minor incremental] (mapv to-long (str/split v #"\."))]
  [major
   (or minor 0)
   (or incremental 0)
   (if q (str/lower-case (re-find #"[^\d]+" q)) "zfinal")
   (some->> q (re-find #"\d+$") to-long)]))
```

at least it makes the following tests pass: 

```clj
(is (= [1 6 0 "alpha" 1] (u/clojure-version->cmp-key "1.6.0-alpha1")))
(is (= [100 234 123 "beta" nil] (u/clojure-version->cmp-key "100.234.123-beta")))
(is (= [0 3 0 "alpha" 1] (u/clojure-version->cmp-key "0.3-alpha1")))
(is (= [0 3 0 "alpha" 15] (u/clojure-version->cmp-key "0.3-ALPHA15")))
```
@arrdem alternative might be to just remove the sorting but not sure how you feel about that?

**Comment by arrdem** [comment]
Removing the sorting altogether is less than ideal - Grimoire as currently implemented relies on versions being in sorted order so that it can show documentation for the "latest" Clojure by default.

Thanks for the patch, I'll try to take a poke at this later today. The ah variety of version suffixes used by Clojure is unfortunate.

**Comment by arrdem** [comment]
I just pushed an `0.10.10` which features this version comparison code and some more tests. It checked out fine in a patched local copy of Grimoire, let me know how it treats you.

**Comment by martinklepsch** [comment]
Thanks @arrdem, seems to be working fine 👍
